#! /bin/bash

echo "::: Installing kernel"
ls -l
python -m echo_kernel.install

echo "::: Listing installed kernels"
jupyter kernelspec list

echo "::: Install and enable tag_execute extension"
jupyter nbextension install nbextension/tag_exec
jupyter nbextension enable tag_exec/main

echo "::: Done"
